### ISSUE TITLE
Correct data type of start date

### ISSUE THREAD

**Issue by felix-seifert** [csgoh/roadmapper#22]
When I try to generate example roadmaps, I sometimes get the error message `TypeError: strptime() argument 1 must be str, not datetime.datetime` for the method `set_timeline`. However, I pass the argument of the start date as `"2023-01-01"`, which should be a string. Naming the argument (`start="2023-01-01"`) often seems to work.

The issue is that method expects a `datetime` while it seems to be okay (and common) to pass it a `str`. If I look through the source code, the argument is usually passed as a `str` (while the method expects a `datetime`). To introduce some more consistency, the expected value should be a `str` which will then be transformed to a `datetime` internally.

**Comment by csgoh** [comment]
Can you provide the code that is able to reproduce the error?

**Comment by csgoh** [comment]
I have added keyword argument for date. You will need to pass in `start="2023-04-24"` when calling `add_timeline()` method.
