### ISSUE TITLE
roadmapper doesn't work in google colab?

### ISSUE THREAD

**Issue by Loughlin-T** [csgoh/roadmapper#44]
Any chance do you know why I can't run this in google colab?

![image](https://github.com/csgoh/roadmapper/assets/77234559/017dbd29-072c-4f43-a0f2-fed5742625e4)

**Comment by csgoh** [comment]
Hi, I think there are two issues with your setup. 

(1) For some reasons the required font does not exist in your Jupyter notebook VM. Please refer to these
https://github.com/csgoh/roadmapper/discussions/34 for resolution.
(2) To run the sample code you copied from README.md, you will need to download the logo file. See this post: https://github.com/csgoh/roadmapper/discussions/43.

Hope this helps.

**Comment by csgoh** [comment]
@Loughlin-T I have not heard from you. I considered this is now resolved and closed.

**Comment by Loughlin-T** [comment]
oh sorry, I was circle back to it soon and will let you know.

thank you for the assistance.

Loughlin
