### ISSUE TITLE
Directory `src/fonts` is very huge

### ISSUE THREAD

**Issue by felix-seifert** [csgoh/roadmapper#51]
The directory `src/fonts` is very huge. I am no specialist in how these files are used in `roadmapper`. Do we need them? Is it possible to remove this directory or at least reduce its size?

The problem with this huge directory is that it impacts the checkout time of the repo. This can be interesting if someone clones the repo to start development. Anyway, the more important part is that we perform the checkout for our CI workflow and we do not always seem to receive a catch hit.

**Comment by csgoh** [comment]
Only two are used (SourceHanSerifTC-Regular.otf and SourceHanSerifTC-Bold.otf). I have removed the unused font files.

**Comment by felix-seifert** [comment]
Nice that you already remove these fonts. :+1: The repo looks now more reasonable.
