### ISSUE TITLE
Bump version of `actions/setup-python`

### ISSUE THREAD

**Issue by felix-seifert** [csgoh/roadmapper#52]
When I created this workflow, the [version of `actions/setup-python` was set to `v4`](https://github.com/csgoh/roadmapper/commit/011a0f688b9aa58f353279528d5229bfcc9b9154). When you updated the workflow, you changed it to `v2`. As it might be nicer to go with more modern versions, I am considering bumping the version. Was there a specific reason you went for this version or can I just bump it?

**Comment by csgoh** [comment]
Hi @felix-seifert , that was not my intention. To be honest, I have no idea what happened. I was just merging your PR to the main branch, I did not changed anything.
