### ISSUE TITLE
Multiple Milestones per task causes incorrect group height

### ISSUE THREAD

**Issue by rickc1588** [csgoh/roadmapper#61]
If you have multiple milestones on one task, the group height increases with the total number of milestones, which makes it too tall. You only need to increase the height once per task with a milestone.

I hacked in this in group.py, which seems to fix the issue

 milestone_count = 0
        for task in self.tasks:
            milestone_count += 1   #len(task.milestones) only need to increase height once per milestone
            if len(task.milestones) == 0:
                for parallel_task in task.tasks:
                    milestone_count += 1    #len(parallel_task.milestones)
                    break  ### We only need to know whether there milestone exists in the parallel tasks

**Comment by csgoh** [comment]
Hi, can you provide your code sample that I can use to recreate the issue?

**Comment by csgoh** [comment]
This has been resolved in v1.3.1

**Comment by rickc1588** [comment]
Tested it and it is fixed. 
Thank You.
