### ISSUE TITLE
text_alignment ignored in milestone

### ISSUE THREAD

**Issue by kajuberdut** [csgoh/roadmapper#75]
The text_alignment attribute exists on the Milestone class but it is never used in the code.
![image](https://github.com/csgoh/roadmapper/assets/8014746/d5a101d9-e4ef-443b-89e1-2fe1d60484e6)

**Comment by csgoh** [comment]
Sorry, this is something that I overlooked.

**Comment by csgoh** [comment]
Hi, Thanks for your contribution! I appreciate it. I have merged your pull request to the main branched and released at as v1.4.0. 

Would you be able to update the Wiki to reflect the support for milestone text alignment?

**Comment by kajuberdut** [comment]
Yes, I will update the wiki. I haven't looked into the level of effort but are you OK if I start working on a future pull request that would add the same level of control to other text alignment?

**Comment by csgoh** [comment]
Yeah, no problem.

**Comment by kajuberdut** [comment]
> Hi, Thanks for your contribution! I appreciate it. I have merged your pull request to the main branched and released at as v1.4.0.
> 
> Would you be able to update the Wiki to reflect the support for milestone text alignment?

I cloned the wiki separately and searched and it doesn't seem that the existing alignment options are mentioned yet. Can you provide some guidance on how you think it's best to add this info.

I am happy to add/update any of these so just let me know which ones are good please:

1. Add text alignment how-to to the snippet about milestones in https://github.com/csgoh/roadmapper/wiki/How-To#how-to-display-milestone-on-tasks
2. Update the sample roadmap with some changes to milestone text alignment (update image and the example code) https://github.com/csgoh/roadmapper/wiki/Sample-Roadmap-Code
3. Add a new how-to section like https://github.com/csgoh/roadmapper/wiki/How-To#how-to-align-text which would explain the advanced text alignment options.

NOTE 1 re: option 2 above: A little concerned adding more information to that example might be too much info.
NOTE 2 re: option 3 above: For now it would have a note that these only work on Milestone until I add the features elsewhere.

**Comment by csgoh** [comment]
Hi, for now, just add another entry (e.g. "How to change milestone text alignment") under this page: https://github.com/csgoh/roadmapper/wiki/How-To

**Comment by kajuberdut** [comment]
I cloned: `https://github.com/csgoh/roadmapper.wiki.git` and made a new branch: `add-milestone-text-alignment-how-to`
but it looks like there is no pull workflow for wiki changes: https://stackoverflow.com/questions/32049506/how-to-access-github-wiki-branches

Sorry, I haven't worked with Github wiki before. Should I just merge my changes into main?

Here is a screenshot of my local preview:
![image](https://github.com/csgoh/roadmapper/assets/8014746/6aeb43eb-6bc5-4143-9760-401ec29911f1)

**Comment by csgoh** [comment]
Hi @kajuberdut, Github wiki is a bit of a pain as I just realised it can't do pull and merge requests. Can you commit and push the changes to the remote repo directly for now? I trust you.

**Comment by kajuberdut** [comment]
Ok, it's done.

https://github.com/csgoh/roadmapper/wiki/How-To#how-to-change-milestone-text-alignment
