### ISSUE TITLE
Milestone diamond can occlude Group label

### ISSUE THREAD

**Issue by kajuberdut** [csgoh/roadmapper#79]
If a milestone is placed in the same position on the X-axis of a group as the text of a group, the milestones diamond occludes the text of the group making it partially or wholly unreadable.

To some extent this can be mitigated by changing the alignment of the group text BUT it would be better if the text remained readable even when these overlap.

Possible solutions:
1. The Milestone diamonds should probably be drawn behind the group text. This might be complicated as I'm not sure if Z level can be controlled with pillow or if this has to be achieved with the draw order.
2. If it is possible to check if the diamond overlaps with text it might be possible to mitigate this by making the diamond smaller, only an outline, making the diamond transparent in a horizontal strip, or in some other way making it possible to read the text that the diamond overlaps.
3. It might be possible to change the default y-axis offset of the diamond or the group text in such a way that this scenario is much less likely to happen or to occlude the text.

**Comment by kajuberdut** [comment]
Example of text being occluded by diamond: 
![image](https://github.com/csgoh/roadmapper/assets/8014746/a29b31fa-4c49-4d6d-8536-254d6ddd7a40)

**Comment by kajuberdut** [comment]
I will make an attempt at a fix for this but wanted to log the issue in case there is already a plan for how to minimize this case.

**Comment by csgoh** [comment]
Thanks @kajuberdut for the suggestions to the issue. Would aligning the task text to the left or right or at certain px/percentage (as you have suggested in the pull request) resolve this in the short term?

I will need some time to think of a better approach for a permanent or long-term solution.

**Comment by kajuberdut** [comment]
Yes, currently changing the size+font size and/or changing the text alignment can work around this.

**Comment by csgoh** [comment]
Hi @kajuberdut 
This is now resolved in v1.5.0. The milestone marker is drawn before the text of the task.
<img width="260" alt="image" src="https://github.com/csgoh/roadmapper/assets/20867152/856c29aa-762e-4d9a-a01d-85be2bf27d96">

Sorry for taking this long. I have been too busy with my work.

**Comment by kajuberdut** [comment]
This is wonderful and thank you!

**Comment by felix-seifert** [comment]
With PR #103, this issue can be closed.
